//
// Generated by Coral
// Generated from IDLImplementation
//

import Foundation

public class CORBA_ORB_Implementation:Implementation,CORBA_ORB
    {
    public override init()
        {
        super.init()
        self.interfaceId = "CORBA::ORB"
        CORBA.orb.registerBOA(CORBA_ORB_BOA.self,forInterfaceId:"CORBA::ORB")
        CORBA.orb.registerImplementation(self,forObjectId: self.objectId)
        }

    public required override init(host:String,port:Int,objectId:String,interfaceId:InterfaceId)
        {
        super.init(host:host,port:port,objectId:objectId,interfaceId:interfaceId)
        }

    // Attributes
    
    
    // NotFound,NotPermitted
    public func destroy(object: CORBA_Object) throws -> Void
        {
        //
        // Put your implementation here
        //
        }
    
    // NotFound,NotPermitted
    public func create(interfaceId: String) throws -> CORBA_Object
        {
        return(Implementation())
        }
    
    }
