//
// Generated by Coral
// Generated from IDLException
//
public class CORBA_ORB_NotFound:CORBA.Exception
    {
    

    

    public override func marshal(on marshaller:IIOPMarshaller)
        {
        marshaller.marshal("CORBA::ORB::NotFound")
        
        }
    }

//
// Generated by Coral
// Generated from IDLExceptionMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CORBA_ORB_NotFound.Type) -> CORBA_ORB_NotFound
        {
        
        let newInstance = CORBA_ORB_NotFound()
        return(newInstance)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CORBA_ORB_NotFound)
        {
        self.marshal("CORBA::ORB::NotFound")
        
        }
    }

