//
// Generated by Coral
// Generated from IDLTypeAlias
//
public typealias CosNaming_BindingList = Array<CosNaming_Binding>

//
// Generated by Coral
// Generated from IDLTypeAliasMarshalling
//

extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_BindingList.Type) -> CosNaming_BindingList
        {
        let count = self.unmarshal(Int.self)
        var elements = Array<CosNaming_Binding>()
        for _ in 0..<count
            {
            elements.append(self.unmarshal(CosNaming_Binding.self))
            }
        return(elements)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_BindingList)
        {
        self.marshal(value.count)
        for element in value
            {
            self.marshal(element)
            }
        }
    }

