//
// Generated by Coral
// Generated from IDLProtocol
//
public protocol CosNaming_NamingContextExt:CosNaming_NamingContext
    {
    
    
    func to_string(name: CosNaming_Name) throws -> CosNaming_StringName
    
    func to_name(stringName: CosNaming_StringName) throws -> CosNaming_Name
    
    func resolve_str(name: CosNaming_StringName) throws -> CORBA_Object
    
    func to_url(address: CosNaming_Address,name: CosNaming_StringName) throws -> CosNaming_URLString
    
    }
