//
// Generated by Coral
// Generated from IDLBOA
//

import Foundation

public class CosNaming_NamingContext_BOA:BasicObjectAdaptor
    {
    public override var interfaceId:InterfaceId
        {
        return(InterfaceId("CosNaming::NamingContext"))
        }

    public override func createInstance() -> CORBA_Object
        {
        return(CosNaming_NamingContext_Implementation())
        }

    public override func respondsTo(operation:String) -> Bool
        {
        switch(operation)
            {
            
            
            case "list":
                return(true)
            
            case "resolve":
                return(true)
            
            case "new_context":
                return(true)
            
            case "unbind":
                return(true)
            
            case "bind_new_context":
                return(true)
            
            case "destroy":
                return(true)
            
            case "rebind_context":
                return(true)
            
            case "rebind":
                return(true)
            
            case "bind":
                return(true)
            
            case "bind_context":
                return(true)
            
            default:
                break
            }
        return(super.respondsTo(operation:operation))
        }

    public override func invoke(operation:String,on:Implementation,outof unmarshaller:IIOPUnmarshaller,into marshaller:IIOPMarshaller) throws
        {
        let instance = on as! CosNaming_NamingContext_Implementation
        switch(operation)
            {
            
            
            case "list":
                
                
                    
                    let how_many = unmarshaller.unmarshal(UInt32.self)
                    
                
                
                
                    
                        
                            var binding_list:CosNaming_BindingList!
                        
                    
                
                
                
                    
                        
                            var binding_iterator:CosNaming_BindingIterator!
                        
                    
                
                
                
                let invocation_result = try instance.list(how_many:how_many,binding_list:&binding_list,binding_iterator:&binding_iterator)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                
                marshaller.marshal(binding_list)
                
                
                
                marshaller.marshal(binding_iterator)
                
                
                marshaller.marshal(invocation_result)
            
            case "resolve":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                let invocation_result = try instance.resolve(n:n)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                marshaller.marshal(invocation_result)
            
            case "new_context":
                
                
                let invocation_result = try instance.new_context()
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                marshaller.marshal(invocation_result)
            
            case "unbind":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                let invocation_result = try instance.unbind(n:n)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                marshaller.marshal(invocation_result)
            
            case "bind_new_context":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                let invocation_result = try instance.bind_new_context(n:n)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                marshaller.marshal(invocation_result)
            
            case "destroy":
                
                
                let invocation_result = try instance.destroy()
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                marshaller.marshal(invocation_result)
            
            case "rebind_context":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                    
                    let naming_context = unmarshaller.unmarshal(CosNaming_NamingContext.self)
                    
                
                
                
                let invocation_result = try instance.rebind_context(n:n,naming_context:naming_context)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                
                
                marshaller.marshal(invocation_result)
            
            case "rebind":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                    
                    let object = unmarshaller.unmarshal(CORBA_Object.self)
                    
                
                
                
                let invocation_result = try instance.rebind(n:n,object:object)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                
                
                marshaller.marshal(invocation_result)
            
            case "bind":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                    
                    let object = unmarshaller.unmarshal(CORBA_Object.self)
                    
                
                
                
                let invocation_result = try instance.bind(n:n,object:object)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                
                
                marshaller.marshal(invocation_result)
            
            case "bind_context":
                
                
                    
                    let n = unmarshaller.unmarshal(CosNaming_Name.self)
                    
                
                
                
                    
                    let naming_context = unmarshaller.unmarshal(CosNaming_NamingContext.self)
                    
                
                
                
                let invocation_result = try instance.bind_context(n:n,naming_context:naming_context)
                
                marshaller.marshal(CORBA.ResultKind.success)
                
                
                
                
                
                marshaller.marshal(invocation_result)
            
        default:
            try super.invoke(operation:operation,on:on,outof:unmarshaller,into:marshaller)
            }
        }
    }
