//
// Generated by Coral
// Generated from IDLImplementation
//

import Foundation

public class CosNaming_NamingContextExt_Implementation:CosNaming_NamingContext_Implementation,CosNaming_NamingContextExt
    {
    public override init()
        {
        super.init()
        self.interfaceId = "CosNaming::NamingContextExt"
        CORBA.orb.registerBOA(CosNaming_NamingContextExt_BOA.self,forInterfaceId:"CosNaming::NamingContextExt")
        CORBA.orb.registerImplementation(self,forObjectId: self.objectId)
        }

    public required override init(host:String,port:Int,objectId:String,interfaceId:InterfaceId)
        {
        super.init(host:host,port:port,objectId:objectId,interfaceId:interfaceId)
        }
    // Attributes
    
    
    // NotFound,CannotProceed,InvalidName
    public func resolve_str(name: CosNaming_StringName) throws -> CORBA_Object?
        {
        return(Implementation())
        }
    
    // InvalidAddress,InvalidName
    public func to_url(address: CosNaming_Address,name: CosNaming_StringName) throws -> CosNaming_URLString
        {
        return("")
        }
    
    // InvalidName
    public func to_string(name: CosNaming_Name) throws -> CosNaming_StringName
        {
        return("")
        }
    
    // InvalidName
    public func to_name(stringName: CosNaming_StringName) throws -> CosNaming_Name
        {
        return([])
        }
    
    }
