//
// Generated by Coral
// Generated from IDLException
//
public class CosNaming_NamingContext_AlreadyBound:CORBA.Exception
    {
    

    

    public override func marshal(on marshaller:IIOPMarshaller)
        {
        marshaller.marshal("CosNaming::NamingContext::AlreadyBound")
        
        }
    }

//
// Generated by Coral
// Generated from IDLExceptionMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_NamingContext_AlreadyBound.Type) -> CosNaming_NamingContext_AlreadyBound
        {
        
        let newInstance = CosNaming_NamingContext_AlreadyBound()
        return(newInstance)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_NamingContext_AlreadyBound)
        {
        self.marshal("CosNaming::NamingContext::AlreadyBound")
        
        }
    }

