//
// Generated by Coral
// Generated from IDLClient
//
//
public class CosNaming_NamingContextExt_Interface:CosNaming_NamingContext_Interface,CosNaming_NamingContextExt
    {
    public override class func interfaceId() -> InterfaceId
        {
        return("CosNaming::NamingContextExt")
        }

    

    public required override init(host:String,port:Int,objectId:String,interfaceId:InterfaceId)
        {
        super.init(host:host,port:port,objectId:objectId,interfaceId:interfaceId)
        }

    

    public static func ==(lhs:CosNaming_NamingContextExt_Interface,rhs:CosNaming_NamingContextExt_Interface) -> Bool
        {
        guard lhs.host == rhs.host else 
            {
            return(false)
            }
        guard lhs.port == rhs.port else
            {
            return(false)
            }
        guard lhs.objectId == rhs.objectId else
            {
            return(false)
            }
        guard lhs.interfaceId == rhs.interfaceId else
            {
            return(false)
            }
        return(true)
        }
        
    
    // [["interfaceId": "CosNaming::NamingContext::InvalidName", "name": "CosNaming_NamingContext_InvalidName"]]
    public func to_string(name: CosNaming_Name) throws -> CosNaming_StringName
        {
        let invocation = self.invocation(forOperation: "to_string")
        let marshaller = invocation.marshaller()
        
            
            marshaller.marshal(name)
            
        
        try invocation.invoke(expect: .response)
        let unmarshaller = invocation.unmarshaller()
        let resultKind = unmarshaller.unmarshal(CORBA.ResultKind.self)
        switch(resultKind)
            {
            case .systemException:
                throw(CORBA.ORBError(rawValue: unmarshaller.unmarshal(Int.self))!)
            case .corbaException:
                
                let exceptionId = unmarshaller.unmarshal(String.self)
                switch(exceptionId)
                    {
                    
                    case "CosNaming::NamingContext::InvalidName":
                        let error = unmarshaller.unmarshal(CosNaming_NamingContext_InvalidName.self)
                        throw(error)
                    
                    default:
                        break
                    }
                
            default:
                break
            }
        
            
        
        return(invocation.unmarshaller().unmarshal(CosNaming_StringName.self))
        }
    
    // [["interfaceId": "CosNaming::NamingContext::InvalidName", "name": "CosNaming_NamingContext_InvalidName"]]
    public func to_name(stringName: CosNaming_StringName) throws -> CosNaming_Name
        {
        let invocation = self.invocation(forOperation: "to_name")
        let marshaller = invocation.marshaller()
        
            
            marshaller.marshal(stringName)
            
        
        try invocation.invoke(expect: .response)
        let unmarshaller = invocation.unmarshaller()
        let resultKind = unmarshaller.unmarshal(CORBA.ResultKind.self)
        switch(resultKind)
            {
            case .systemException:
                throw(CORBA.ORBError(rawValue: unmarshaller.unmarshal(Int.self))!)
            case .corbaException:
                
                let exceptionId = unmarshaller.unmarshal(String.self)
                switch(exceptionId)
                    {
                    
                    case "CosNaming::NamingContext::InvalidName":
                        let error = unmarshaller.unmarshal(CosNaming_NamingContext_InvalidName.self)
                        throw(error)
                    
                    default:
                        break
                    }
                
            default:
                break
            }
        
            
        
        return(invocation.unmarshaller().unmarshal(CosNaming_Name.self))
        }
    
    // [["interfaceId": "CosNaming::NamingContext::NotFound", "name": "CosNaming_NamingContext_NotFound"], ["interfaceId": "CosNaming::NamingContext::CannotProceed", "name": "CosNaming_NamingContext_CannotProceed"], ["interfaceId": "CosNaming::NamingContext::InvalidName", "name": "CosNaming_NamingContext_InvalidName"]]
    public func resolve_str(name: CosNaming_StringName) throws -> CORBA_Object
        {
        let invocation = self.invocation(forOperation: "resolve_str")
        let marshaller = invocation.marshaller()
        
            
            marshaller.marshal(name)
            
        
        try invocation.invoke(expect: .response)
        let unmarshaller = invocation.unmarshaller()
        let resultKind = unmarshaller.unmarshal(CORBA.ResultKind.self)
        switch(resultKind)
            {
            case .systemException:
                throw(CORBA.ORBError(rawValue: unmarshaller.unmarshal(Int.self))!)
            case .corbaException:
                
                let exceptionId = unmarshaller.unmarshal(String.self)
                switch(exceptionId)
                    {
                    
                    case "CosNaming::NamingContext::NotFound":
                        let error = unmarshaller.unmarshal(CosNaming_NamingContext_NotFound.self)
                        throw(error)
                    
                    case "CosNaming::NamingContext::CannotProceed":
                        let error = unmarshaller.unmarshal(CosNaming_NamingContext_CannotProceed.self)
                        throw(error)
                    
                    case "CosNaming::NamingContext::InvalidName":
                        let error = unmarshaller.unmarshal(CosNaming_NamingContext_InvalidName.self)
                        throw(error)
                    
                    default:
                        break
                    }
                
            default:
                break
            }
        
            
        
        return(invocation.unmarshaller().unmarshal(CORBA_Object.self))
        }
    
    // [["interfaceId": "CosNaming::InvalidAddress", "name": "CosNaming_InvalidAddress"], ["interfaceId": "CosNaming::NamingContext::InvalidName", "name": "CosNaming_NamingContext_InvalidName"]]
    public func to_url(address: CosNaming_Address,name: CosNaming_StringName) throws -> CosNaming_URLString
        {
        let invocation = self.invocation(forOperation: "to_url")
        let marshaller = invocation.marshaller()
        
            
            marshaller.marshal(address)
            
        
            
            marshaller.marshal(name)
            
        
        try invocation.invoke(expect: .response)
        let unmarshaller = invocation.unmarshaller()
        let resultKind = unmarshaller.unmarshal(CORBA.ResultKind.self)
        switch(resultKind)
            {
            case .systemException:
                throw(CORBA.ORBError(rawValue: unmarshaller.unmarshal(Int.self))!)
            case .corbaException:
                
                let exceptionId = unmarshaller.unmarshal(String.self)
                switch(exceptionId)
                    {
                    
                    case "CosNaming::InvalidAddress":
                        let error = unmarshaller.unmarshal(CosNaming_InvalidAddress.self)
                        throw(error)
                    
                    case "CosNaming::NamingContext::InvalidName":
                        let error = unmarshaller.unmarshal(CosNaming_NamingContext_InvalidName.self)
                        throw(error)
                    
                    default:
                        break
                    }
                
            default:
                break
            }
        
            
        
            
        
        return(invocation.unmarshaller().unmarshal(CosNaming_URLString.self))
        }
    
    }


//
// Generated by Coral
// Generated from IDLClientMarshalling
//
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value: CosNaming_NamingContextExt.Protocol) -> CosNaming_NamingContextExt
        {
        let host = self.unmarshal(String.self)
        let port = self.unmarshal(Int.self)
        let objectId = self.unmarshal(String.self)
        let interfaceId = self.unmarshal(String.self)
        return(CosNaming_NamingContextExt_Interface(host:host,port:port,objectId:objectId,interfaceId:InterfaceId(interfaceId)))
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value: CosNaming_NamingContextExt)
        {
        self.marshal(value.host)
        self.marshal(value.port)
        self.marshal(value.objectId)
        self.marshal(value.interfaceId)
        }
    }
