//
// Generated by Coral
// Generated from IDLException
//
public class CosNaming_InvalidAddress:CORBA.Exception
    {
    

    

    public override func marshal(on marshaller:IIOPMarshaller)
        {
        marshaller.marshal("CosNaming::InvalidAddress")
        
        }
    }

//
// Generated by Coral
// Generated from IDLExceptionMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_InvalidAddress.Type) -> CosNaming_InvalidAddress
        {
        
        let newInstance = CosNaming_InvalidAddress()
        return(newInstance)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_InvalidAddress)
        {
        self.marshal("CosNaming::InvalidAddress")
        
        }
    }

