//
// Generated by Coral
// Generated from IDLException
//
public class CosNaming_NamingContext_InvalidName:CORBA.Exception
    {
    

    

    public override func marshal(on marshaller:IIOPMarshaller)
        {
        marshaller.marshal("CosNaming::NamingContext::InvalidName")
        
        }
    }

//
// Generated by Coral
// Generated from IDLExceptionMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_NamingContext_InvalidName.Type) -> CosNaming_NamingContext_InvalidName
        {
        
        let newInstance = CosNaming_NamingContext_InvalidName()
        return(newInstance)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_NamingContext_InvalidName)
        {
        self.marshal("CosNaming::NamingContext::InvalidName")
        
        }
    }

