//
// Generated by Coral
// Generated from IDLException
//
public class CosNaming_NamingContext_NotFound:CORBA.Exception
    {
    
        var why:CosNaming_NamingContext_NotFoundReason
    
        var rest_of_name:CosNaming_Name
    

    
    public init(why:CosNaming_NamingContext_NotFoundReason,rest_of_name:CosNaming_Name)
        {
        
        self.why = why
        
        self.rest_of_name = rest_of_name
        
        }
    

    public override func marshal(on marshaller:IIOPMarshaller)
        {
        marshaller.marshal("CosNaming::NamingContext::NotFound")
        
        marshaller.marshal(self.why)
        
        marshaller.marshal(self.rest_of_name)
        
        }
    }

//
// Generated by Coral
// Generated from IDLExceptionMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_NamingContext_NotFound.Type) -> CosNaming_NamingContext_NotFound
        {
        
        let why = self.unmarshal(CosNaming_NamingContext_NotFoundReason.self)
        
        let rest_of_name = self.unmarshal(CosNaming_Name.self)
        
        let newInstance = CosNaming_NamingContext_NotFound(why:why,rest_of_name:rest_of_name)
        return(newInstance)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_NamingContext_NotFound)
        {
        self.marshal("CosNaming::NamingContext::NotFound")
        
        self.marshal(value.why)
        
        self.marshal(value.rest_of_name)
        
        }
    }

