//
// Generated by Coral
// Generated from IDLEnum
//
public enum CosNaming_NamingContext_NotFoundReason:Int
    {
    
    case missing_node
    
    case not_context
    
    case not_object
    
    }



//
// Generated by Coral
// Generated from IDLEnumMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_NamingContext_NotFoundReason.Type) -> CosNaming_NamingContext_NotFoundReason
        {
        let rawValue = self.unmarshal(Int.self)
        return(CosNaming_NamingContext_NotFoundReason(rawValue: rawValue)!)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_NamingContext_NotFoundReason)
        {
        self.marshal(value.rawValue)
        }
    }

