//
// Generated by Coral
// Generated from IDLStruct
//
//
public struct CosNaming_Binding
    {
    
        var binding_name:CosNaming_Name
    
        var binding_type:CosNaming_BindingType
    

    public init(binding_name:CosNaming_Name,binding_type:CosNaming_BindingType)
        {
        
        self.binding_name = binding_name
        
        self.binding_type = binding_type
        
        }
    }


//
// Generated by Coral
// Generated from IDLStructMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_Binding.Type) -> CosNaming_Binding
        {
        
        let binding_name = self.unmarshal(CosNaming_Name.self)
        
        let binding_type = self.unmarshal(CosNaming_BindingType.self)
        
        let newInstance = CosNaming_Binding(binding_name:binding_name,binding_type:binding_type)
        return(newInstance)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_Binding)
        {
        
        self.marshal(value.binding_name)
        
        self.marshal(value.binding_type)
        
        }
    }
