//
// Generated by Coral
// Generated from IDLEnum
//
public enum CosNaming_BindingType:Int
    {
    
    case nobject
    
    case ncontext
    
    }



//
// Generated by Coral
// Generated from IDLEnumMarshalling
//
extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_BindingType.Type) -> CosNaming_BindingType
        {
        let rawValue = self.unmarshal(Int.self)
        return(CosNaming_BindingType(rawValue: rawValue)!)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_BindingType)
        {
        self.marshal(value.rawValue)
        }
    }

