//
// Generated by Coral
// Generated from IDLTypeAlias
//
public typealias CosNaming_Name = Array<CosNaming_NameComponent>

//
// Generated by Coral
// Generated from IDLTypeAliasMarshalling
//

extension IIOPUnmarshaller
    {
    public func unmarshal(_ value:CosNaming_Name.Type) -> CosNaming_Name
        {
        let count = self.unmarshal(Int.self)
        var elements = Array<CosNaming_NameComponent>()
        for _ in 0..<count
            {
            elements.append(self.unmarshal(CosNaming_NameComponent.self))
            }
        return(elements)
        }
    }

extension IIOPMarshaller
    {
    public func marshal(_ value:CosNaming_Name)
        {
        self.marshal(value.count)
        for element in value
            {
            self.marshal(element)
            }
        }
    }

